# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financ.Pessoa')),
                ('cpf', models.CharField(max_length=15)),
            ],
            bases=('financ.pessoa',),
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cnpjCpf',
        ),
    ]
