# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financ', '0002_auto_20170419_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('EmpresaId', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financ.Pessoa')),
                ('cnpj', models.CharField(max_length=15)),
                ('inscricaoEstadual', models.CharField(max_length=20)),
                ('inscricaoMunicipal', models.CharField(max_length=20)),
            ],
            bases=('financ.pessoa',),
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='tipoPessoa',
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsalvelId',
            field=models.ForeignKey(on_delete='pessoa_ptr', to='financ.PessoaJuridica', to_field='pessoaId'),
        ),
    ]
